name: "Update Environment"

on:
  push:
    branches:
      - "main"
    paths:
      - "env/**"
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Deployment Target
        required: false
        default: www-staging
        options:
          - "www-staging"
          - "www-production"

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: ${{ inputs.target == '' && 'www-staging' || inputs.target }}
      WORKSPACE_TAGS: ${{ vars.WORKSPACE_TAGS }}
      TERRAFORM_ORGANIZATION: ${{ vars.TERRAFORM_ORGANIZATION }}
      TFRC: ${{ secrets.TERRAFORM_CREDS }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Credentials
        run: |
          echo Setting up credentials
          mkdir ~/.terraform.d
          echo $TFRC > ~/.terraform.d/credentials.tfrc.json
      - name: Initialize Terraform
        run: |
          echo Will use workspace: $TF_WORKSPACE
          terraform init -var TERRAFORM_ORGANIZATION=${TERRAFORM_ORGANIZATION}
          terraform workspace show
      - name: Apply Configuration
        run: terraform plan
