name: "Update Environment"

on:
  push:
    branches:
      - "main"
      - "staging"
  workflow_dispatch:

jobs:
  apply:
    name: Apply Configuration
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    env:
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
      WORKSPACE_TAGS: ${{ vars.WORKSPACE_TAGS }}
      TERRAFORM_ORGANIZATION: ${{ vars.TERRAFORM_ORGANIZATION }}
      TFRC: ${{ secrets.TERRAFORM_CREDS }}
      INPUTS: ${{ vars.TERRAFORM_INPUTS }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Credentials
        run: |
          echo Setting up credentials
          mkdir ~/.terraform.d
          echo $TFRC > ~/.terraform.d/credentials.tfrc.json
      - name: Setup Terraform
        run: |
          echo Will use workspace: $TF_WORKSPACE
          terraform init -var TERRAFORM_ORGANIZATION=${TERRAFORM_ORGANIZATION}
          terraform workspace list
      - name: Apply Configuration
        run: terraform apply --auto-approve
